version: '3.7'

services:

  service-dashboard:
    stdin_open: true
    build:
      context: .
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
